#!/usr/bin/env python3
"""
Copyright (c) 2020 Antmicro

Simple LiteX configuration parser.

This script parses LiteX 'csr.csv' file and allows to extract
information from it.
"""

import sys
import argparse

from litex.configuration import Configuration


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('conf_file',
                        help='CSV configuration generated by LiteX')
    parser.add_argument('--constant', action='store',
                        help='Print constant value')
    parser.add_argument('--csr_base', action='store',
                        help='Print CSR base address')
    parser.add_argument('--memory_base', action='store',
                        help='Print memory base address')
    args = parser.parse_args()

    return args


def main():
    global configuration
    args = parse_args()

    configuration = Configuration(args.conf_file)

    if args.constant:
        if args.constant not in configuration.constants:
            print("Constant '{}' not found in the configuration".format(args.constant), file=sys.stderr)
            sys.exit(1)
        print(configuration.constants[args.constant]["value"])

    if args.csr_base:
        if args.csr_base not in configuration.peripherals:
            print("Peripheral '{}' not found in the configuration".format(args.csr_base), file=sys.stderr)
            sys.exit(1)
        print(configuration.peripherals[args.csr_base]["address"])

    if args.memory_base:
        if args.memory_base not in configuration.mem_regions:
            print("Memory region '{}' not found in the configuration".format(args.memory_base), file=sys.stderr)
            sys.exit(1)
        print(configuration.mem_regions[args.memory_base]["address"])


if __name__ == '__main__':
    main()
